In [19]:
#Array rotation once

a=[1,2,3,4,5,6,7,8]
#output=[2,3,4,5,6,7,8,1]

#for loop
def rotate(a):
    a1=a[0]
    for i in range(len(a)):
        if i==len(a)-1:
            a[i]=a1
        else:
            a[i]=a[i+1]
    return a
rotate(a)
    


[2, 3, 4, 5, 6, 7, 8, 1]

In [1]:
#for loop but skipping if
from array import array
a=array('i',[1,2,3,4,5])
def rotate(a):
    a1=a[0]
    for i in range(len(a)-1):
        a[i]=a[i+1]
    a[-1]=a1
    return a
rotate(a)

array('i', [2, 3, 4, 5, 1])

In [13]:
#Rotating twice
a= array('i',[1,2,3,4,5])
for i in range(0,2):
    a1=a[0]
    for j in range(len(a)-1):
        a[j]=a[j+1]
    a[-1]=a1
a

array('i', [3, 4, 5, 1, 2])

In [14]:
b=a[2:]+a[:2]
a

array('i', [3, 4, 5, 1, 2])

###### Monotone or not 

In [31]:
#Monotone or not  #either strictly increasing or strictly decreasing
arr=[5,10,15,20]
def monotone(arr):
    sum1=0
    for i in range(len(arr)-1):
        sum1+=arr[i]<=arr[i+1]
    sum2=0
    for i in range(len(arr)-1):
        sum2+=arr[i]>=arr[i+1]
    return sum1==len(arr)-1 or sum2==len(arr)-1
monotone(arr)



True

In [25]:
arr=[10,9,8,7,6,6,5,5,5]
monotone(arr)

True

In [26]:
arr=[10,34,56,32,9]
monotone(arr)

False

In [34]:
def monotone(arr):
    return (all(arr[i]<=arr[i+1] for i in range(len(arr)-1)) or all(arr[i]>=arr[i+1] for i in range(len(arr)-1)))

In [35]:
monotone(arr)

True

# LIST

1 Swap first and last element

In [2]:
#method1
a=[1,2,3,4,5]
def swap(a):
    a[0],a[-1]=a[-1],a[0]
    return a
swap(a)

[5, 2, 3, 4, 1]

In [5]:
#method 2
a=[1,2,3,4,5,6]
def swap1(a):
    first=a[0]
    last=a[-1]
    a[0]=last
    a[-1]=first
    return a
swap1(a)

[6, 2, 3, 4, 5, 1]

In [16]:
#method3
a=[1,2,3,4,5,6]
a1=a[:1]
a2=a[1:-1]
a3=a[-1:]
b=a3+a2+a1
b

[6, 2, 3, 4, 5, 1]

In [20]:
#method4
a=[1,2,3,4,5]
first,*middle,last=a
b=[last,*middle,first]
b

[5, 2, 3, 4, 1]

In [24]:
frst,mdle,last=a[:1],a[1:-1],a[-1:]

2 Python Program to Swap Two Elements in a List


In [29]:
#method1
a=[1,2,3,4,5,6]
def swapany(arr,pos1,pos2):
    #pos1 and pos2 takes position of elements need to swapped
    arr[pos2-1],arr[pos1-1]=arr[pos1-1],arr[pos2-1]
    return arr
swapany(a,1,3)

[3, 2, 1, 4, 5, 6]

In [1]:
#using pop and insert method
a=[1,2,3,4,5,6]

def swap(arr,pos1,pos2):
    first=arr.pop(pos1-1)
    second=arr.pop(pos2-2)
    arr.insert(pos1-1,second)
    arr.insert(pos2-1,first)
    return arr
swap(a,1,3)

[3, 2, 1, 4, 5, 6]

3 Check whether given element exist in list or not

In [2]:
#using in operator
a=[1,2,3,3,4,5,6]
def exist(a,b):
     return b in (a)
exist(a,3)

True

In [3]:
#using any and lsit concatenation
a=[1,2,3,4,5,6]
b=7
any([i==b for i in a])

False

In [7]:
#using iteration
def exist_(inpt,b):
    for i in inpt:
        if i==b:
            return True
    return False

exist_(a,b)

False

In [9]:
exist_(a,4)

True

4 Clear the list

In [3]:
#using clear method
a=[1,2,3,4]
a.clear()
a

[]

In [3]:
#Reinitialising
a=[1,2,3,4]
a=[]
a

[]

In [28]:
#Using pop
a=[1,2,3,4]
i=0
while len(a)!=0:
    a.pop(i)
a

[]

In [4]:
#using remove function
a=[1,2,3,4]
b=a[:]
for i in b:
    a.remove(i)
a

[]

In [31]:
a=[1,2,3,4]

for i in range(len(a)):
    a.pop(0)
a

[]

5 Reversing list in python

In [49]:
#using list.reverse
a=[1,2,3,4,5]
a.reverse()
a

[5, 4, 3, 2, 1]

In [58]:
#using while
a=[1,2,3,4,5,6,7]
def reverse_(a):
        i=0
        j=len(a)-1
        while i!=len(a)//2:
            a[i],a[j]=a[j],a[i]
            i+=1
            j-=1
        return a
reverse_(a)

[7, 6, 5, 4, 3, 2, 1]

In [68]:
#using reversed
a=[1,2,3,4]
[i for i in reversed(a)]


[4, 3, 2, 1]

In [5]:
#using for loop and insert
a=[1,2,3,4]
b=[]
for i in a:
    b.insert(0,i)
b

[4, 3, 2, 1]

In [10]:
#using for loop

def revrse(a):
    for i in range(len(a)//2):
        a[i],a[-i-1]=a[-i-1],a[i]
    return a
revrse([1,2,3,4,5])

[5, 4, 3, 2, 1]

In [6]:
#list comprehension
a=[1,2,3,4]
[a[len(a)-i] for i in range(1,len(a)+1)]

[4, 3, 2, 1]

In [7]:
#list comprehension 2
a=[1,2,3,4,5]
[a[len(a)-i-1] for i in range(len(a))]

[5, 4, 3, 2, 1]

In [9]:
#comprehension 3
[a[-i] for i in range(1,len(a)+1)]

[5, 4, 3, 2, 1]

6 Find sum of element in list

In [16]:
a=[1,2,3,4,5]

In [17]:
# using sum method
sum(a)

15

In [18]:
#using reduce method
from functools import reduce
def sum_(list_):
    return reduce(lambda a,b:a+b,list_)
sum_(a)

15

In [19]:
# using for loop
sum_=0
for i in a:
    sum_+=i
sum_
    

15

In [2]:
#using while loop:
a=[1,2,3,4,5]
i=0
sum_=0
while i <len(a):
    sum_+=a[i]
    i+=1
sum_

15

7 multiply all elements in the list.

In [3]:
# using reduce
from functools import reduce

a=[1,2,3,4]
def prdct(ar):
    return reduce(lambda a,b:a*b ,ar)
prdct(a)

24

In [4]:
#using for loop
a=[1,2,3,4]
prdct=1
for i in a:
    prdct*=i
prdct
  

24

In [1]:
#using while loop
a=[1,2,3,4]

i=0
prdct=1
while i <len(a):
    prdct*=a[i]
    i+=1
prdct

24

8 Find smallest element in given list.

In [77]:
#using min

a=[2,3,1,4]
min(a)

1

In [82]:
#using for loop

def small(a):
    sml=a[0]
    for i in a:
        if i <=sml:
            sml=i
        
    return sml
small(a)

1

In [80]:
small([10, 20, 4])

4

In [83]:
#using numpy
import numpy as np
np.min(a)

1

In [89]:
#using sorted function
a=[10, 20, 4]
sorted(a)[0]


4

In [90]:
#using sort function
a.sort()
a[0]

4

In [91]:
#sort and reverse
a.sort(reverse=True)
a[-1]

4

9 Find maximum element in the given list.

In [3]:
#Max element in list
a=[10,20,4]
max(a)

20

In [4]:
sorted(a)[-1]

20

In [100]:
a.sort(reverse=True)
a[0]

20

In [101]:
np.max(a)

20

In [103]:
a=[10, 20, 4, 45, 99]
b=a[0]
i=1
while i <len(a):
    if a[i]>b:
        b=a[i]
    i+=1
b

99

10. Find Second largest number in given list

In [111]:
#method 1 
a=[10, 20, 4, 45,45,35,35,99, 99]
def scnd_large(a):
    if len(a)==1:
        return a[0]
    elif len(a)==2:
        return min(a)
    else:
        mx1=max(a[0],a[1])
        mx2=min(a[0],a[1])
        for i in range(2,len(a)):
            if a[i]>mx1:
                mx2=mx1
                mx1=a[i]
            elif a[i]<mx1 and a[i]>mx2:
                mx2=a[i]
        return mx2

In [112]:
scnd_large(a)

45

In [9]:
#method 2
a=[0,2,3,3]
def scnd(a):
    lrgst=a[0]
    scndlrg=0
    for i in range(1,len(a)):
        if a[i]>lrgst and lrgst>scndlrg:
            scndlrg=lrgst
            lrgst=a[i]
        elif a[i]>lrgst and lrgst<=scndlrg:
            lrgst=a[i]
        elif a[i]<lrgst and a[i]>scndlrg:
            scndlrg=a[i]
    return scndlrg
    
scnd(a)

2

In [8]:
#method 3
def scnd(a):
    lrg=a[0]
    for i in range(1,len(a)):
        if a[i]>lrg:
            lrg=a[i]
    while lrg in a:
        a.remove(lrg)
    lrg=a[0]
    for i in range(1,len(a)):
        if a[i]>lrg:
            lrg=a[i]
    return lrg

scnd([100,30,100,45,6])
            

45

In [118]:
b=list(set(a))  #becuse if there is rptn we get wrong output so we make set so no rptn
b.sort
b[-2]

45

In [123]:
a=[10, 20, 4, 45,45,35,35,99, 99]
b=[i for i in a if i< max(a)]
max(b)

45

11. Find n largest numbers in given list

In [1]:
#using for loop
a=[5,1,4,3,2]

def n_large(a,n):
    n_largest=[]
    b=a.copy()
    for i in range(n):
        mx=b[0]
        for j in range(len(b)):
            if b[j]>mx:
                mx=b[j]
        n_largest.append(mx)
        b.remove(mx)
    return n_largest
n_large(a,3)

[5, 4, 3]

In [124]:
#using sort
a=[81, 52, 45, 10, 3, 2, 96] 
def n_max(a,n):
    a.sort(reverse=True)
    return a[:n]
n_max(a,3)

[96, 81, 52]

In [127]:
def max_n(a,n):
    a.sort()
    return a[-n:]
max_n(a,3)

[52, 81, 96]

In [134]:
#using max
def max1(a,n):
    b=[]
    for i in range(n):
        b.append(max(a))
        a.remove(max(a))
    return b
 
a=[81, 52, 45, 10, 3, 2, 96]
max1(a,3)

[96, 81, 52]

In [138]:
#Using numpy
a=[81, 52, 45, 10, 3, 2, 96]
ar=np.array(a)
ar[ar.argsort()[-3:]]

array([52, 81, 96])

12. Find even numbers in the given list.

In [148]:
# True/Flase indexing
a=[1,2,3]
a=np.array(a)
a[[i%2==0 for i in a ]]

array([2])

In [149]:
#List comprehension
[i for i in a if i%2==0]

[2]

13. Find odd numbers in the given range

In [2]:
#using map and for loop
input_=input('Eneter starting point and end points (leave space between numbers)')
start,end=map(int,input_.split())
for i in range(start,end+1):
     print(i,end=' ') if i%2!=0 else None
                                            

Eneter starting point and end points (leave space between numbers)2 10
3 5 7 9 

The map() function in Python is used to apply a specified function to each item in an iterable (e.g., a list, tuple, or string) and return an iterable (usually a map object) containing the results. It's a way to transform or apply a function to every element of a sequence without explicitly writing a loop.

In [11]:
#Using filter and lambda method
def odds_(start,end):
    li=[i for i in range(start,end+1)]
    return list(filter(lambda a : a%2!=0 ,li))
odds_(3,9)   
    
    

[3, 5, 7, 9]

14. Find positive numbers in the given list

In [1]:
#using while loop
a = [12, -7, 5, 64, -14]
i=0
while i<len(a):
    print(a[i],end=" ") if a[i]>0 else None
    
    i+=1
    

12 5 64 

In [14]:
#using filter function
a = [12, -7, 5, 64, -14]

def pos(a):
    return list(filter(lambda i: i>0 , a))
pos(a)

[12, 5, 64]

In [3]:
#recursion
def pos1(start,list_):
    if start==len(list_):
        return
    if list_[start]>0 :
        print(list_[start],end=" ")
    pos1(start+1,list_)

In [7]:
a = [12, -7, 5, 64, -14]

j=pos1(0,a)


12 5 64 

In [27]:
#By using property of string

a = [12, -7, 0, 5, 64, -14] 

def pos2(a):
    b=list(map(str,a))
    i=0
    c=[]
    while i < len(b) :
        c.append(b[i]) if (not b[i].startswith('-') and b[i]!='0') else None
        i+=1
    return list(map(int,c))

pos2(a)
        

[12, 5, 64]

In [10]:
#using numpy

import numpy as np

a = [12, -7, 5, 64, -14]

a=np.array(a)
a[a>0]

array([12,  5, 64])

15.  Python program to print all positive number in a given range

In [9]:
# using recursion method
def pos(start,ending):
    if start==ending:
        return
    if start>0:
        print(start,end=" ")
    pos(start+1,ending)
    return

pos(-4,3)

1 2 

In [7]:
# while loop
input_=input('enter the range')
start,end=list(map(int,input_.split()))
i=start
while i  in range(start,end):
    if i>0:
        print (i,end=" ")
    i+=1

enter the range-4 5
1 2 3 4 

In [8]:
#for loop
def pos_(start , ending):
    for i in range (start,ending):
        print(i,end=" ") if i >0 else None
pos_(-4,5)       

1 2 3 4 

In [10]:
#list comprehension
def pos(a,b):
    return [i for i in range(a,b) if i>0]
pos(-2,4)

[1, 2, 3]

In [11]:
a=-2
b=3
c=[i for i in range(a,b)]
list(filter(lambda a : a>0,c))

[1, 2]

In [12]:
list(filter(lambda a: a>0 ,range(a,b)))

[1, 2]

16. Find negative numbers.

In [10]:
#list comprehension
a = [12, -7, 5, 64, -14]
neg=[i for i in a if i<0]
neg

[-7, -14]

In [20]:
#while loop
neg=[]
i=0
while i <len(a):
    neg.append(a[i]) if a[i] <0 else None
    i+=1
neg

[-7, -14]

In [22]:
#using  filter
a = [12, -7, 5, 64, -14]
list(filter(lambda i : i<0,a))

[-7, -14]

In [24]:
#recursion:
def neg(a,start):  #note assing 0 to start while calling this function
    if start==len(a):
        return
    if a[start]<0:
        print(a[start],end=" ")
    neg(a,start+1)
neg(a,0)   

-7 -14 

In [31]:
#by making  elements as string 
a = [12, -7, 0, 5, 64, -14]
def neg1(a):
    b=list(map(str,a))
    return list(map(int ,[i for i in b if i.startswith('-')]))
neg1(a)

[-7, -14]

In [32]:
# using numpy
import numpy as np
a=np.array(a)
a[a<0]

array([ -7, -14])

In [34]:
a = [12, -7, 5, 64, -14]
b=np.array(a)
b[np.where(b<0)]

array([ -7, -14])

In [40]:
#reduce

from functools import reduce
 
list1 = [-10, -21, -4, 45, -66, 93]

reduce(lambda a,b:a+[b] if b<0 else a ,list1,[])
#append cant be useddirectlty in reduce i.e y we r using a+[b] list addition

[-10, -21, -4, -66]

17. Remove desired element from list.

In [1]:
#filter method

a=[1,2,3,4,'hi']
unwanted=[3,'hi']

list(filter(lambda x : x not in unwanted,a))

[1, 2, 4]

In [16]:
# list comprehension

a=[1,2,3,2,4,5,6,7]
unwanted=[2,5,7]
a=[i for i in a if i not in unwanted]
a

[1, 3, 4, 6]

In [5]:
#for loop

a=[5,1,2,3,2,4,5,6,7]
unwanted=[2,5,7]
for  i in a :
    if i in unwanted: a.remove(i)
a

[1, 3, 4, 6]

In [4]:
# for and while

a=[5,1,2,3,2,4,5,6,7]
unwanted=[2,5,7]
for i in unwanted:
    while i in a:
        a.remove(i)
a

[1, 3, 4, 6]

In [2]:
#while loop

i=0
a=[1,2,3,2,4,5,6,7]
unwanted=[2,5,7]
while i <len(a):
    if a[i] in unwanted:a.remove(a[i])
    i+=1
a

[1, 3, 4, 6]

18. Remove empty list from list

In [4]:
#list comprehension
a = [ 3, [], [], 95, 6, []]

a=[i for i in a if not i==[]]
a

[3, 95, 6]

In [2]:
#using filter
a = [ 3, [], [], 95, 6, []]

a=list(filter(lambda a: a!=[],a))
a

[3, 95, 6]

In [3]:
#using remove function
a = [ 3, [], [], 95, 6, []]
while [] in a:
    a.remove([])
a

[3, 95, 6]

In [2]:
#using filter method
a = [ 3, [], [], 9,5, 6, []]
list(filter(None , a))

[3, 9, 5, 6]

In [6]:
#recursion
def remove_(start,original,final):
    if start==len(original):
        return final
    if original[start]!=[]:
        final.append(original[start])
    return remove_(start+1,original,final)
a = [ 3, [], [], 9,5, 6, []]
remove_(0,a,[])

[3, 9, 5, 6]

19. Cloning or copying list

In [9]:
a=[1,2,3,4,5,6]
b=a[:]
b

[1, 2, 3, 4, 5, 6]

In [10]:
d=[i for i in a]
d[0]=100
print(d)
print(a)

[100, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6]


In [11]:
import copy
c=copy.copy(a)
c[0]=10
a

[1, 2, 3, 4, 5, 6]

In [12]:
f=a.copy()
f[0]=1
a

[1, 2, 3, 4, 5, 6]

20. Given a list in Python and a number x, count the number of occurrences of x in the given list.

In [29]:
lst = [1,2,3,1,2,3,3,4,5]
def count_(lst,x):
    count=0
    for i in lst:
        count+=1 if i==x else 0
    return count
count_(lst,3)

3

In [13]:
lst = [1,2,3,1,2,3,3,4,5]
from functools import reduce
def count_0(lst,x):
    return reduce(lambda a,b:a+1 if b==x else a+0,lst,0)
count_0(lst,3)

3

In [52]:
def count_1(lst,x):
    return sum(1 if i==x else 0 for i in lst)
count_1(lst,3)    

3

In [41]:
#using recursion
def count_2(lst,x,start,count):
    """ lst is list need to inspected
    x is the values whose count you require
    start is the index from which you need to start searching
    count is empty lis []"""
    if start==len(lst):
        return sum(count)
    if lst[start]==x:
        count.append(1)
    return count_2(lst,x,start+1,count)
count_2(lst,1,0,[])

2

In [16]:
def count_3(lst,x,count,start):
    "start and count must be 0"
    if start==len(lst):
        return count
    if lst[start]==x:
        count+=1
    return count_3(lst,x,start+1,count)
count_3(lst,3,0,0)

9

In [60]:
a=[1,2,2,3,3,3,4]
count_3(lst,4,0,0)

1

In [64]:
#using count function
a=[1,2,2,3,3,3,4]
a.count(2)

2

In [67]:
#Dictionary comprehension
a=[1,2,2,3,3,3,4]
count={item:a.count(item) for item in a }
count

{1: 1, 2: 2, 3: 3, 4: 1}

In [69]:
lst = [1,2,3,1,2,3,3,4,5,3]

def count_5(lst,x):
    return len([i for i in lst if i==x])
count_5(lst,3)

4

In [71]:
from collections import Counter
d=Counter(lst
         )
d

Counter({1: 2, 2: 2, 3: 4, 4: 1, 5: 1})

In [77]:
lst = [1,2,3,1,2,3,3,4,5,3]
def count_(lst,x):
    def count_1(sublist):
        if not sublist:
            return 0
        if sublist:
            first,end=sublist[0],sublist[1:]
        return (1 if first==x else 0)+ count_1(end)
    return count_1(lst)
count_(lst,3)

4

22. Remove empty tuples from a list.

In [19]:
lst=[(), ('ram','15','8'), (), ('laxman', 'sita'), ('krishna', 'akbar', '45'), (","),()]

In [20]:
#list comprehension    
def remove(lst):
    return [i for i in lst if  not i==()]
remove(lst)

[('ram', '15', '8'), ('laxman', 'sita'), ('krishna', 'akbar', '45'), ',']

In [21]:
#Recursion
def remove_(lst,start,cleaned):
    if start==len(lst):
        return cleaned
    if lst[start]:
        cleaned.append(lst[start])
    return remove_(lst,start+1,cleaned)
remove_(lst,0,[])

[('ram', '15', '8'), ('laxman', 'sita'), ('krishna', 'akbar', '45'), ',']

In [107]:
#recursion #removes any empty either (  or [])
lst=[(), ('ram','15','8'), (), ('laxman', 'sita'), ('krishna', 'akbar', '45'), (","),(),[]]
def remove_(lst):
    if not lst:
        return []
    first,end=lst[0:1],lst[1:]
    return (first if first[0] else [])+remove_(end)
remove_(lst)

[('ram', '15', '8'), ('laxman', 'sita'), ('krishna', 'akbar', '45'), ',']

In [113]:
lst=[(), ('ram','15','8'), (), ('laxman', 'sita'), ('krishna', 'akbar', '45'), (","),()]
list(filter(None,lst))

[('ram', '15', '8'), ('laxman', 'sita'), ('krishna', 'akbar', '45'), ',']

23. write python code to obtain below given ouput  for the given input 

inputs :  list1=[x,  y] , list2=[z,  e]
    
output= list1=[x,  e]  list2=[y,  z]

In [11]:
list1=[10,20]
list2=[100,200]
i=0
j=-1
while i<len(list1):
    print(list1[i],list2[j])
    i+=1
    j-=1

10 200
20 100


In [15]:
for i ,j in zip(list1,list2[::-1]):
    print(i,j)

10 200
20 100


24. Find the mode in given list

In [10]:
def mode(inpt):
    unique=[]
    for i in inpt:
        if i not in unique:
            unique.append(i)
    count=[]
    for i in unique:
        counter=0
        for j in inpt:
            if i==j:
                counter+=1
        count.append(counter)
    for x,z in zip(unique,count):
        if z==max(count):
            print(x,end=" ")

a=[1,2,3,1,2,3,2,2] #mode 2
b=[1,2,3,1,2,3,2,2,1,1]  #mode 1,2
mode(a)
print()   
mode(b)

2 
1 2 