#### ARRAY


If builtn using python module array.array you canot directly remove element or add new element. You can reasign values by indexing.

###### Find the sum

In [2]:
from array import array
def sum_(arr):
    sum1=0
    for i in arr:
        sum1+=i
    return sum1
a=array('i',[1,2,3])
sum_(a)

6

In [4]:
from functools import reduce
def sum_(arr):
    return reduce(lambda a ,b : a+b,arr)
sum_(array('i',[2,3,4]))

9

reduce(lambda a, b: a + b, arr), performs a cumulative operation on the elements of the given iterable (arr) using the specified lambda function (lambda a, b: a + b). Let's break down what happens at each step of this operation:

First Step:

a is the first element of the iterable (arr[0]).
b is the second element of the iterable (arr[1]).
The lambda function lambda a, b: a + b is applied to these two elements: a + b.
The result of the lambda function becomes the new value of a.
Second Step:

a is now the result of the previous step (arr[0] + arr[1]).
b is the third element of the iterable (arr[2]).
The lambda function is applied again: (arr[0] + arr[1]) + arr[2].
The result of the lambda function becomes the new value of a.
Third Step:

a is now the result of the previous step (arr[0] + arr[1] + arr[2]).
b is the fourth element of the iterable (arr[3]).
The lambda function is applied again: ((arr[0] + arr[1]) + arr[2]) + arr[3].
The process continues until all elements in the iterable have been processed. At each step, the lambda function accumulates the result by adding the current element to the accumulated value (a).

For example, let's consider the arr list as [12, 3, 4, 15]:

First step: a = 12, b = 3, lambda a, b: a + b evaluates to 15, so a becomes 15.
Second step: a = 15, b = 4, lambda a, b: a + b evaluates to 19, so a becomes 19.
Third step: a = 19, b = 15, lambda a, b: a + b evaluates to 34.
The final result, 34, is the sum of all elements in the array.

In [24]:
#recursion
def sum_(arr,start):
    if start==len(arr):
            return 0
    else :                             
        return arr[start]+sum_(arr,start+1)   

In [17]:
from array import array
a=array('i',[1,2,3])
sum_(a,0)

6

In [23]:
def sum_1(arr,start):
    if start==len(arr):
        return 0
    if start<len(arr):
        return arr[start]+sum_1(arr,start+1)
sum_1(a,0)


6

In [2]:
from array import array
def sum_1(arr):
    if arr :
        return arr[0]+sum_1(arr[1:])
    else:
        return 0
    
    
a=array('i',[1,2,3])    
sum_1(a)

6

###### Largest in array

In [27]:
#FINDING LARGEST ELEMENT IN THE ARray
import numpy as np
from array import array
#for loop
a=array('i',[4,3,5,6,1])
def largest(a):                 #note it doesnot work if all elemnets are -ve
    large=a[0]
    for i in a:
        if i>large:
            large=i
    return large
largest(a)


6

In [6]:
np.max(a)

6

In [9]:
#while loop
def largest1(a):
    large=0
    i=0
    while i < len(a):
        if a[i]>large:
            large=a[i]
        i+=1
    return large
largest1(a)
        

6

In [16]:
a=array('i',[4,3,5,6,1])
from functools import reduce
reduce(lambda c,b : max(c,b),a)


6

In [2]:
a=[1,2,3,[],()]
list(filter(None,a))

[1, 2, 3]

###### Rotating array once

In [19]:
#Array rotation once

a=[1,2,3,4,5,6,7,8]
#output=[2,3,4,5,6,7,8,1]

#for loop
def rotate(a):
    a1=a[0]
    for i in range(len(a)):
        if i==len(a)-1:
            a[i]=a1
        else:
            a[i]=a[i+1]
    return a
rotate(a)
    


[2, 3, 4, 5, 6, 7, 8, 1]

In [1]:
#for loop but skipping if
from array import array
a=array('i',[1,2,3,4,5])
def rotate(a):
    a1=a[0]
    for i in range(len(a)-1):
        a[i]=a[i+1]
    a[-1]=a1
    return a
rotate(a)

array('i', [2, 3, 4, 5, 1])

In [13]:
#Rotating twice
a= array('i',[1,2,3,4,5])
for i in range(0,2):
    a1=a[0]
    for j in range(len(a)-1):
        a[j]=a[j+1]
    a[-1]=a1
a

array('i', [3, 4, 5, 1, 2])

In [14]:
b=a[2:]+a[:2]
a

array('i', [3, 4, 5, 1, 2])

###### FInd product of array then devide by given no and return remainder

In [4]:
#Array multiply devideby given number and return remainder
arr = [100, 10, 5, 25, 35, 14]
def rmndr(arr,n):
    prdct=1        #for
    for i in (arr):
        prdct*=i
    return prdct%n
rmndr(arr,11)

9

In [5]:
from functools import reduce  #reduce
def rmndr(arr,n):
    return reduce(lambda a,b: a*b , arr)%n
rmndr(arr,11)

9

In [23]:
#while
def rmndr(arr,n):
    i=0
    prdct=1
    while i <len(arr) :
        prdct*=arr[i]
        i+=1
    return prdct%n
rmndr(arr,11)

9

###### Monotone or not 

In [31]:
#Monotone or not  #either strictly increasing or strictly decreasing
arr=[5,10,15,20]
def monotone(arr):
    sum1=0
    for i in range(len(arr)-1):
        sum1+=arr[i]<=arr[i+1]
    sum2=0
    for i in range(len(arr)-1):
        sum2+=arr[i]>=arr[i+1]
    return sum1==len(arr)-1 or sum2==len(arr)-1
monotone(arr)



True

In [25]:
arr=[10,9,8,7,6,6,5,5,5]
monotone(arr)

True

In [26]:
arr=[10,34,56,32,9]
monotone(arr)

False

In [34]:
def monotone(arr):
    return (all(arr[i]<=arr[i+1] for i in range(len(arr)-1)) or all(arr[i]>=arr[i+1] for i in range(len(arr)-1)))

In [35]:
monotone(arr)

True

# LIST

In [2]:
#Swap first and last element
a=[1,2,3,4,5]
def swap(a):
    a[0],a[-1]=a[-1],a[0]
    return a
swap(a)

[5, 2, 3, 4, 1]

In [5]:
a=[1,2,3,4,5,6]
def swap1(a):
    first=a[0]
    last=a[-1]
    a[0]=last
    a[-1]=first
    return a
swap1(a)

[6, 2, 3, 4, 5, 1]

In [16]:
a=[1,2,3,4,5,6]
a1=a[:1]
a2=a[1:-1]
a3=a[-1:]
b=a3+a2+a1
b

[6, 2, 3, 4, 5, 1]

In [20]:
a=[1,2,3,4,5]
first,*middle,last=a
b=[last,*middle,first]
b

[5, 2, 3, 4, 1]

In [24]:
frst,mdle,last=a[:1],a[1:-1],a[-1:]

In [29]:
#Python Program to Swap Two Elements in a List

a=[1,2,3,4,5,6]
def swapany(arr,pos1,pos2):
    arr[pos2-1],arr[pos1-1]=arr[pos1-1],arr[pos2-1]
    return arr
swapany(a,1,3)

[3, 2, 1, 4, 5, 6]

In [2]:
a=[1,2,3,4,5,6]

def swap(arr,pos1,pos2):
    first=arr.pop(pos1-1)
    second=arr.pop(pos2-2)
    arr.insert(pos1-1,second)
    arr.insert(pos2-1,first)
    return arr
swap(a,1,3)

[3, 2, 1, 4, 5, 6]

In [3]:
# len of list
len(a)

6

In [8]:
ln=0
for i in a :
    ln+=1
ln

6

In [9]:
sum(1 for i in a)

6

In [27]:
#Check element exist in python or not
a=[1,2,3,3,4,5,6]
def exist(a,b):
     return b in (a)
exist(a,3)

True

In [3]:
a=[1,2,3,4,5,6]
b=7
any([i==b for i in a])

False

In [7]:
def exist_(inpt,b):
    for i in inpt:
        if i==b:
            return True
    return False

exist_(a,b)

False

In [9]:
exist_(a,4)

True

In [2]:
#Clear the list

a=[1,2,3,4]
a.clear()
a

[]

In [3]:
#Reinitialising
a=[1,2,3,4]
a=[]
a

[]

In [28]:
#Using pop
a=[1,2,3,4]
i=0
while len(a)!=0:
    a.pop(i)
a

[]

In [47]:
a=[1,2,3,4]
b=a[:]
for i in a:
    b.remove(i)
b

[]

In [31]:
a=[1,2,3,4]

for i in range(len(a)):
    a.pop(0)
a

[]

In [49]:
#Reversing list in python
a=[1,2,3,4,5]
a.reverse()
a

[5, 4, 3, 2, 1]

In [58]:
a=[1,2,3,4,5,6,7]
def reverse_(a):
        i=0
        j=len(a)-1
        while i!=len(a)//2:
            a[i],a[j]=a[j],a[i]
            i+=1
            j-=1
        return a
reverse_(a)

[7, 6, 5, 4, 3, 2, 1]

In [68]:
a=[1,2,3,4]
[i for i in reversed(a)]


[4, 3, 2, 1]

In [70]:
a=[1,2,3,4]
b=[]
for i in a:
    b.insert(0,i)
b

[4, 3, 2, 1]

In [71]:
#list comprehension
[a[len(a)-i] for i in range(1,len(a)+1)]

[4, 3, 2, 1]

In [73]:
[a[len(a)-i-1] for i in range(len(a))]

[4, 3, 2, 1]

In [74]:
#product
a=[1,2,3,4]
def prdct(ar):
    return reduce(lambda a,b:a*b ,ar)
prdct(a)

24

In [77]:
#Smallest number in list

a=[2,3,1,4]
min(a)

1

In [82]:
def small(a):
    sml=a[0]
    for i in a:
        if i <=sml:
            sml=i
        
    return sml
small(a)

1

In [80]:
small([10, 20, 4])

4

In [83]:
import numpy as np
np.min(a)

1

In [89]:
a=[10, 20, 4]
sorted(a)[0]


4

In [90]:
a.sort()
a[0]

4

In [91]:
a.sort(reverse=True)
a[-1]

4

In [93]:
#Max element in list
a=[10,20,4]
max(a)

20

In [94]:
sorted(a)[-1]

20

In [100]:
a.sort(reverse=True)
a[0]

20

In [101]:
np.max(a)

20

In [103]:
a=[10, 20, 4, 45, 99]
b=a[0]
i=1
while i <len(a):
    if a[i]>b:
        b=a[i]
    i+=1
b

99

In [111]:
#Second largest numbedr
a=[10, 20, 4, 45,45,35,35,99, 99]
def scnd_large(a):
    if len(a)==1:
        return a[0]
    elif len(a)==2:
        return min(a)
    else:
        mx1=max(a[0],a[1])
        mx2=min(a[0],a[1])
        for i in range(2,len(a)):
            if a[i]>mx1:
                mx2=mx1
                mx1=a[i]
            elif a[i]<mx1 and a[i]>mx2:
                mx2=a[i]
        return mx2

In [112]:
scnd_large(a)

45

In [118]:
b=list(set(a))  #becuse if there is rptn we get wrong output so we make set so no rptn
b.sort
b[-2]

45

In [119]:
a.sort(reverse=True)
a[1]  #See actly 45 but wse get 99 due to reptetion 

99

In [123]:
a=[10, 20, 4, 45,45,35,35,99, 99]
b=[i for i in a if i< max(a)]
max(b)

45

In [124]:
#Find n largest number
a=[81, 52, 45, 10, 3, 2, 96] 
def n_max(a,n):
    a.sort(reverse=True)
    return a[:n]
n_max(a,3)

[96, 81, 52]

In [127]:
def max_n(a,n):
    a.sort()
    return a[-n:]
max_n(a,3)

[52, 81, 96]

In [134]:
def max1(a,n):
    b=[]
    for i in range(n):
        b.append(max(a))
        a.remove(max(a))
    return b
 
a=[81, 52, 45, 10, 3, 2, 96]
max1(a,3)

[96, 81, 52]

In [138]:
#Using numpy
a=[81, 52, 45, 10, 3, 2, 96]
ar=np.array(a)
ar[ar.argsort()[-3:]]

array([52, 81, 96])

In [148]:
#To get even numbers
a=[1,2,3]
a=np.array(a)
a[[i%2==0 for i in a ]]

array([2])

In [149]:
[i for i in a if i%2==0]

[2]

In [1]:
input_=input('Eneter starting point and end points (leave space between numbers)')
start,end=map(int,input_.split())
for i in range(start,end+1):
     print(i,end=' ') if i%2!=0 else None
                                            #imp

Eneter starting point and end points (leave space between numbers)3 9
3 5 7 9 

Note if list consist of string you cant directly convert it into int u should loop it

The map() function in Python is used to apply a specified function to each item in an iterable (e.g., a list, tuple, or string) and return an iterable (usually a map object) containing the results. It's a way to transform or apply a function to every element of a sequence without explicitly writing a loop.

In [11]:
def odds_(start,end):
    li=[i for i in range(start,end+1)]
    return list(filter(lambda a : a%2!=0 ,li))
odds_(3,9)   
    
    

[3, 5, 7, 9]

In [1]:
# Positive number
a = [12, -7, 5, 64, -14]
i=0
while i<len(a):
    print(a[i],end=" ") if a[i]>0 else None
    
    i+=1
    

12 5 64 

In [14]:
a = [12, -7, 5, 64, -14]

def pos(a):
    return list(filter(lambda i: i>0 , a))
pos(a)

[12, 5, 64]

In [8]:
#recursion
def pos1(start,list_):
    if start==len(list_):
        return
    if list_[start]>0 :
        print(list_[start],end=" ")
    pos1(start+1,list_)

In [9]:
a = [12, -7, 5, 64, -14]

pos1(0,a)

12 5 64 

In [10]:
#using numpy

import numpy as np

a = [12, -7, 5, 64, -14]

a=np.array(a)
a[a>0]

array([12,  5, 64])

In [27]:
#By using property of string

a = [12, -7, 0, 5, 64, -14] 

def pos2(a):
    b=list(map(str,a))
    i=0
    c=[]
    while i < len(b) :
        c.append(b[i]) if (not b[i].startswith('-') and b[i]!='0') else None
        i+=1
    return list(map(int,c))

pos2(a)
        

[12, 5, 64]

In [4]:
#Python program to print all positive in a given range

def pos(start,ending):
    if start==ending:
        return
    if start>0:
        print(start,end=" ")
    pos(start+1,ending)
    return

pos(-4,3)

1 2 

In [7]:
input_=input('enter the range')
start,end=list(map(int,input_.split()))
i=start
while i  in range(start,end):
    if i>0:
        print (i,end=" ")
    i+=1

enter the range-4 5
1 2 3 4 

In [8]:
def pos_(start , ending):
    for i in range (start,ending):
        print(i,end=" ") if i >0 else None
pos_(-4,5)       

1 2 3 4 

In [10]:
def pos(a,b):
    return [i for i in range(a,b) if i>0]
pos(-2,4)

[1, 2, 3]

In [11]:
a=-2
b=3
c=[i for i in range(a,b)]
list(filter(lambda a : a>0,c))

[1, 2]

In [12]:
list(filter(lambda a: a>0 ,range(a,b)))

[1, 2]

In [19]:
# print negative number
a = [12, -7, 5, 64, -14]
neg=[i for i in a if i<0]
neg

[-7, -14]

In [20]:
neg=[]
i=0
while i <len(a):
    neg.append(a[i]) if a[i] <0 else None
    i+=1
neg

[-7, -14]

In [22]:
#using lambda and filter
a = [12, -7, 5, 64, -14]
list(filter(lambda i : i<0,a))

[-7, -14]

In [24]:
#recursion:
def neg(a,start):  #note assing 0 to start while calling this function
    if start==len(a):
        return
    if a[start]<0:
        print(a[start],end=" ")
    neg(a,start+1)
neg(a,0)   

-7 -14 

In [31]:
#by making  elements as string 
a = [12, -7, 0, 5, 64, -14]
def neg1(a):
    b=list(map(str,a))
    return list(map(int ,[i for i in b if i.startswith('-')]))
neg1(a)

[-7, -14]

In [32]:
# using numpy
import numpy as np
a=np.array(a)
a[a<0]

array([ -7, -14])

In [34]:
a = [12, -7, 5, 64, -14]
b=np.array(a)
b[np.where(b<0)]

array([ -7, -14])

In [40]:
#reduce

from functools import reduce
 
list1 = [-10, -21, -4, 45, -66, 93]

reduce(lambda a,b:a+[b] if b<0 else a ,list1,[])
#append cant be useddirectlty in reduce i.e y we r using a+[b] list addition

[-10, -21, -4, -66]

In [16]:
#Remove desired elemnt
a=[1,2,3,2,4,5,6,7]
unwanted=[2,5,7]
a=[i for i in a if i not in unwanted]
a

[1, 3, 4, 6]

In [5]:
a=[5,1,2,3,2,4,5,6,7]
unwanted=[2,5,7]
for  i in a :
    if i in unwanted: a.remove(i)
a

[1, 3, 4, 6]

In [4]:
a=[5,1,2,3,2,4,5,6,7]
unwanted=[2,5,7]
for i in unwanted:
    while i in a:
        a.remove(i)
a

[1, 3, 4, 6]

In [42]:
i=0
a=[1,2,3,2,4,5,6,7]
unwanted=[2,5,7]
while i <len(a):
    if a[i] in unwanted:a.remove(a[i])
    i+=1
a

[1, 3, 4, 6]

# continue

In [1]:
# Remove empty List from List
a = [ 3, [], [], 95, 6, []]
#list comprehension
a=[i for i in a if not i==[]]
a

[3, 95, 6]

In [2]:
a = [ 3, [], [], 95, 6, []]
#using filter
a=list(filter(lambda a: a!=[],a))
a

[3, 95, 6]

In [3]:
a = [ 3, [], [], 95, 6, []]
while [] in a:
    a.remove([])
a

[3, 95, 6]

In [1]:
a = [ 3, [], [], 95, 6, []]
b=list(map(str,a))
b="".join(b)
b=b.replace('[]',"")
b=list(map(int,b))
b

[3, 9, 5, 6]

In [2]:
a = [ 3, [], [], 9,5, 6, []]
list(filter(None , a))

[3, 9, 5, 6]

In [6]:
#recursion
def remove_(start,original,final):
    if start==len(original):
        return final
    if original[start]!=[]:
        final.append(original[start])
    return remove_(start+1,original,final)
a = [ 3, [], [], 9,5, 6, []]
remove_(0,a,[])

[3, 9, 5, 6]

###### Clonign the list

In [9]:
a=[1,2,3,4,5,6]
b=a[:]
b

[1, 2, 3, 4, 5, 6]

In [17]:
b=a
b[0]=100   #a also gets altered
print(b)
print(a)

[100, 2, 3, 4, 5, 6]
[100, 2, 3, 4, 5, 6]


In [15]:
d=[i for i in a]
d[0]=100
print(d)
print(a)

[1, 2, 3, 4, 5, 6]

In [14]:
import copy
c=copy.copy(a)
c[0]=10
a

[1, 2, 3, 4, 5, 6]

In [20]:
f=a.copy()
f[0]=1
a

[100, 2, 3, 4, 5, 6]

###### Given a list in Python and a number x, count the number of occurrences of x in the given list.

In [29]:
lst = [1,2,3,1,2,3,3,4,5]
def count_(lst,x):
    count=0
    for i in lst:
        count+=1 if i==x else 0
    return count
count_(lst,3)

3

In [111]:
lst = [1,2,3,1,2,3,3,4,5]
from functools import reduce
def count_0(lst,x):
    return reduce(lambda a,b:a+1 if b==x else a+0,lst,0)
count_0(lst,3)

3

In [52]:
def count_1(lst,x):
    return sum(1 if i==x else 0 for i in lst)
count_1(lst,3)    

3

In [41]:
#using recursion
def count_2(lst,x,start,count):
    """ lst is list need to inspected
    x is the values whose count you require
    start is the index from which you need to start searching
    count is empty lis []"""
    if start==len(lst):
        return sum(count)
    if lst[start]==x:
        count.append(1)
    return count_2(lst,x,start+1,count)
count_2(lst,1,0,[])

2

In [63]:
def count_3(lst,x,start,count):
    "start and count must be 0"
    if start==len(lst):
        return count
    if lst[start]==x:
        count+=1
    return count_3(lst,x,start+1,count)
count_3(lst,3,0,0)

3

In [60]:
a=[1,2,2,3,3,3,4]
count_3(lst,4,0,0)

1

In [64]:
#using count function
a=[1,2,2,3,3,3,4]
a.count(2)

2

In [67]:
#Dictionary comprehension
a=[1,2,2,3,3,3,4]
count={item:a.count(item) for item in a }
count

{1: 1, 2: 2, 3: 3, 4: 1}

In [69]:
lst = [1,2,3,1,2,3,3,4,5,3]

def count_5(lst,x):
    return len([i for i in lst if i==x])
count_5(lst,3)

4

In [71]:
from collections import Counter
d=Counter(lst
         )
d

Counter({1: 2, 2: 2, 3: 4, 4: 1, 5: 1})

In [77]:
lst = [1,2,3,1,2,3,3,4,5,3]
def count_(lst,x):
    def count_1(sublist):
        if not sublist:
            return 0
        if sublist:
            first,end=sublist[0],sublist[1:]
        return (1 if first==x else 0)+ count_1(end)
    return count_1(lst)
count_(lst,3)

4

###### Remove empty tuples from a list

In [92]:
lst=[(), ('ram','15','8'), (), ('laxman', 'sita'), ('krishna', 'akbar', '45'), (","),()]

In [93]:
def remove(lst):
    return [i for i in lst if  not i==()]
remove(lst)

[('ram', '15', '8'), ('laxman', 'sita'), ('krishna', 'akbar', '45'), ',']

In [95]:
#Recursion
def remove_(lst,start,cleaned):
    if start==len(lst):
        return cleaned
    if lst[start]:
        cleaned.append(lst[start])
    return remove_(lst,start+1,cleaned)
remove_(lst,0,[])

[('ram', '15', '8'), ('laxman', 'sita'), ('krishna', 'akbar', '45'), ',']

In [107]:
#recursion #removes any empty either (  or [])
lst=[(), ('ram','15','8'), (), ('laxman', 'sita'), ('krishna', 'akbar', '45'), (","),(),[]]
def remove_(lst):
    if not lst:
        return []
    first,end=lst[0:1],lst[1:]
    return (first if first[0] else [])+remove_(end)
remove_(lst)

[('ram', '15', '8'), ('laxman', 'sita'), ('krishna', 'akbar', '45'), ',']

In [113]:
lst=[(), ('ram','15','8'), (), ('laxman', 'sita'), ('krishna', 'akbar', '45'), (","),()]
list(filter(None,lst))

[('ram', '15', '8'), ('laxman', 'sita'), ('krishna', 'akbar', '45'), ',']

In [11]:
list1=[10,20]
list2=[100,200]
i=0
j=-1
while i<len(list1):
    print(list1[i],list2[j])
    i+=1
    j-=1

10 200
20 100


In [15]:
for i ,j in zip(list1,list2[::-1]):
    print(i,j)

10 200
20 100


In [23]:
a=399
for i in range(a):
    print(a%10,end="")
    a=a//10
    if a==0:
        break

993

In [25]:
def revers(n):
    rev=0
    while n>0:
        rev=rev*10+n%10
        n=n//10
    return rev
revers(245)

542

In [2]:
#Finding Mode

a=[1,2,3,1,2,3,2,2]
def mode(inpt):
    Unique=[]
    for i in a:
        if i not in Unique:
            Unique.append(i)
            
    mode=None
    count=0
    for i in Unique:
        Temp_count=0
        for j in inpt:
            if i==j:
                Temp_count+=1
        if Temp_count>count:
            count=Temp_count
            mode=i
    return mode
mode(a)

2

In [10]:
def mode(inpt):
    unique=[]
    for i in inpt:
        if i not in unique:
            unique.append(i)
    count=[]
    for i in unique:
        counter=0
        for j in inpt:
            if i==j:
                counter+=1
        count.append(counter)
    for x,z in zip(unique,count):
        if z==max(count):
            print(x,end=" ")

a=[1,2,3,1,2,3,2,2] #mode 2
b=[1,2,3,1,2,3,2,2,1,1]  #mode 1,2
mode(a)
print()   
mode(b)

2 
1 2 

In [15]:
a=[1,2,3,1,2,3,2,2,1,1]
def md(a):
    n=None
    count=0
    for i in set(a):
        if a.count(i)>count:
            count=a.count(i)
            n=i
    return n
md(a)       

1